import React from 'react'

const Features = () => {
  return (
    <div id='features' className='w-full h-screen bg-gradient-to-r from-gray-200 text-white mt-10'>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Qui, sequi maiores doloremque id molestias, asperiores quod dolores tempore, aut dolor quaerat! Corrupti aliquid esse libero quidem repellat modi aperiam veritatis.
      Deserunt fuga odio ut doloremque laborum totam voluptatibus aliquid omnis qui nemo laboriosam consequuntur, sit reiciendis ullam corporis, aliquam quod assumenda mollitia explicabo est ea vitae obcaecati dolores. Deleniti, accusamus?
      Culpa sequi, maxime labore est ab nobis illo magnam itaque animi omnis, cum dolorum quia aut consequatur consectetur quae nostrum qui doloremque necessitatibus unde tempore suscipit. Repellendus cumque dolore illo.
      Rem expedita pariatur natus porro aperiam omnis ad. Libero quos voluptatibus qui quasi alias veniam accusantium eveniet facilis odio voluptatum. Praesentium, excepturi accusantium temporibus porro exercitationem nihil et suscipit corporis.
      Natus doloribus minus est quidem officia pariatur perspiciatis vitae recusandae veniam velit rerum accusamus molestiae, itaque ratione ipsum cupiditate quasi facilis cum. Odit, itaque quasi debitis atque rem facilis quae!
      Delectus asperiores fugit nostrum, a aut id corporis sed rerum porro, aperiam itaque necessitatibus earum expedita dicta fuga repellat eaque molestias. Eius dolor tempore quasi. Fuga tempore reiciendis consequatur quidem.
      Cupiditate, consectetur? Dolor delectus tempora deserunt adipisci id consectetur neque omnis molestiae dicta eveniet in reiciendis hic aperiam numquam et praesentium natus, corrupti atque molestias, nihil ab. Quas, iusto eos.
      Unde eius quae, amet impedit iste aut deserunt consectetur obcaecati vero, id fuga officia, dicta necessitatibus ipsam blanditiis ad debitis! Odio mollitia atque voluptate culpa, numquam fugit minima exercitationem cumque?
      Eligendi dolorem est quo nemo ad, illum eum consequatur fugit necessitatibus tempora incidunt quibusdam accusantium architecto id. Eveniet quae tenetur corporis ex placeat deserunt adipisci tempore, omnis autem perferendis quas.
      Assumenda alias, ea illum sed velit quas labore recusandae commodi facilis dolores. Aperiam excepturi vitae porro ad voluptate corporis id quibusdam quis. Sed pariatur sapiente dolore necessitatibus voluptatum blanditiis? Illo.
      Debitis minima amet explicabo porro impedit in architecto qui tempora! Dolor accusamus ab eos, quos molestias ducimus amet velit nostrum quia fugiat provident laboriosam? Rem cum necessitatibus deserunt explicabo inventore!
      Illum alias odit nobis dolores expedita nisi voluptate deserunt repudiandae, nostrum, voluptatem ut. Quas ad enim, ab fugiat minus voluptatibus dolorem officiis quasi et sint assumenda, harum voluptas expedita. Veritatis?
      Aliquam, quos accusantium, id asperiores laudantium ipsa eum deleniti blanditiis tempore odio ducimus ullam quam impedit maxime repellendus eius? Delectus mollitia culpa dolorum voluptates autem voluptatibus earum quia sint. Harum!
      Nobis ut, delectus dicta eos beatae recusandae eveniet necessitatibus totam. Fugiat voluptatem nostrum quod et aspernatur asperiores veritatis vel, modi blanditiis iste tempore animi consectetur quo dignissimos beatae delectus quam.
      Praesentium placeat vel eos dolorem similique fugiat voluptates nulla? Facere consequatur esse ullam assumenda unde dignissimos. Nam, animi quibusdam voluptas veritatis sequi veniam maxime officiis, quia soluta magni praesentium odio.
      Vero magnam quisquam sed delectus assumenda nisi commodi! Tempore harum iure dolorem maxime, et natus laborum placeat libero id. Corrupti deserunt ipsa error earum totam dicta perspiciatis eveniet, rem quod?
      Fuga neque optio corrupti officiis eveniet dignissimos debitis aperiam reiciendis, molestias earum natus tenetur illum quidem consequuntur itaque, esse sequi distinctio inventore minus ullam iure! Voluptatibus vitae omnis dolorem possimus!
      Facere labore architecto fugit, est tenetur quos aliquam ipsa iusto a! Reiciendis sapiente, rem doloribus pariatur consectetur temporibus a laboriosam eius, quae, magnam voluptatibus cum minus voluptates ipsa veritatis illo.
      Delectus accusamus debitis, cum omnis voluptates tenetur vero neque. Alias odit iusto quidem sit tenetur, incidunt vero dolor perferendis autem, voluptatibus eius, optio blanditiis. Quidem blanditiis error dolores temporibus veritatis.
      Architecto saepe beatae iste numquam? Magni reprehenderit libero labore iure error assumenda doloremque blanditiis tenetur quidem tempora id quasi iusto odit voluptatum, impedit molestias eveniet quaerat consectetur? Reprehenderit, labore impedit.
      Ipsam voluptates tempore numquam consectetur eum aliquam asperiores ut rerum error, velit dolores aliquid cupiditate sapiente nobis, pariatur saepe. Consequuntur eius perspiciatis quod! Dolor nesciunt eveniet dolore! Porro, excepturi omnis.
      Nostrum molestiae at blanditiis repellat veniam dolores asperiores. Voluptatibus voluptas nostrum quia est dicta architecto asperiores ipsum sed totam autem? Quas quibusdam repellendus optio quisquam itaque, adipisci cum voluptate consequuntur.
      Labore voluptates nemo ipsa, quas ullam illum facilis eos provident hic distinctio tempora ducimus dolores quae iste. A dolorem alias placeat sequi earum unde. Alias, architecto. Soluta, iure! Eaque, labore!
      Vel laborum assumenda repellat quasi culpa, inventore quidem saepe expedita voluptatum magnam, quisquam consequuntur, et neque quibusdam cum consequatur rem hic necessitatibus iusto in recusandae aliquam pariatur at? Illum, dolor.
      Dolore rem nam minima? Qui hic fugit vero dignissimos, error saepe nemo, quis veniam officiis a ab odio magni eligendi quidem omnis unde laborum. Deserunt eum illo maxime cum pariatur.
      Aliquid eligendi, cum sequi quae sed non officia! Reprehenderit, dolor laudantium atque architecto aut sapiente, ipsam numquam cumque corrupti officiis maxime eos magni voluptas maiores facilis necessitatibus velit ab hic.
      Harum, hic explicabo commodi aperiam sit numquam ab deserunt nesciunt debitis unde est soluta! Impedit, quidem vitae facilis porro ullam laborum possimus illo laudantium sunt rem explicabo corporis dolor. Nesciunt?
      Sed eveniet nobis possimus excepturi. Maiores deleniti eaque aliquid error sapiente ab culpa soluta dolorem assumenda possimus ipsam a voluptas libero rem minima consequatur molestiae animi, at repudiandae quibusdam aperiam.
      Repellat nemo, itaque minima cumque beatae esse perferendis sunt dolore, rerum magnam excepturi obcaecati veniam vel quos eius facilis minus voluptates tenetur? Quasi architecto quis magnam laudantium natus porro perferendis.
      Repellat beatae earum sint inventore, nostrum eius iusto, ex exercitationem unde ad aspernatur ea iure magnam itaque, autem molestias repudiandae iste reprehenderit minima culpa quis? Ipsum vel et praesentium magnam?
      Laborum exercitationem natus eligendi repellat doloremque. Repudiandae voluptatibus eaque ut sunt accusamus esse explicabo illo. Fugit at aspernatur optio totam qui quia inventore error quidem pariatur. Facere impedit mollitia accusantium?
      Architecto totam ut, cupiditate consequuntur quod alias at ad numquam ipsa ullam quos velit assumenda ducimus quaerat corporis quisquam aliquid odio earum nostrum! Hic fugit quos temporibus quas nostrum eum!
      Hic neque quo quam fugiat repellendus omnis cum, vitae, deleniti explicabo suscipit, debitis dolore ex recusandae id. Non magni at ratione illo quaerat corporis beatae. Esse tenetur quibusdam iste veniam!
      Quisquam, harum ex. Porro quis quae aliquam facere magni aliquid impedit vero praesentium laborum illum ipsam officia aspernatur beatae enim, dolorum libero adipisci error ipsa quam veniam rerum at? Fuga.
      Rem suscipit aliquam totam esse repellat, asperiores magni voluptas sint ut repellendus numquam, unde molestias! Molestiae perspiciatis odit aspernatur laborum vel, mollitia excepturi sint accusamus unde voluptate in. Nesciunt, dolores.
      Inventore, optio dolorum? Fugit dicta veritatis repellat, nemo vel sint officiis deserunt cum, doloremque consequatur itaque perferendis tempore assumenda ex vitae? Voluptate voluptatem repudiandae nihil eius? Placeat suscipit autem eaque?
      Fuga odio pariatur asperiores, blanditiis aut delectus optio nihil. Earum, explicabo delectus sed officiis culpa asperiores expedita nisi? Velit voluptatem mollitia blanditiis! Velit, at id modi sit dignissimos assumenda. Quasi.
      Iure libero possimus molestiae, officia reiciendis quibusdam et dolorem ex saepe? Accusantium modi molestiae optio adipisci soluta cumque nesciunt non vitae corporis, nobis omnis possimus esse quas dicta! Suscipit, repellat!
      Fugit pariatur ipsum illo, porro in obcaecati ratione? Totam similique quam commodi nisi? Accusamus, nemo! Repellat distinctio accusantium consequatur harum adipisci, molestias laborum fuga numquam! Quia culpa eos officia eaque.
      Assumenda aspernatur deleniti, amet a officia dignissimos facilis. Cumque, ex. Eos distinctio tempora maxime eius sint animi quibusdam corporis possimus sit perspiciatis reiciendis labore perferendis, necessitatibus qui illum asperiores rerum!
      Consectetur porro corrupti aperiam vero consequatur deserunt sed inventore maiores nemo autem? Reiciendis, error doloremque. Rerum, autem at error molestias nisi quia quos, recusandae fugiat, perferendis exercitationem velit laborum voluptatem?
      Impedit, nihil iure vel, saepe facilis sed provident accusantium, vero ratione et minima hic nulla! Exercitationem mollitia, cum enim officiis neque quod numquam earum nam totam amet adipisci possimus atque.
      Cupiditate perspiciatis tempora nulla fugit laudantium nesciunt illo dicta et ducimus adipisci quis, omnis corporis ullam reiciendis laboriosam eos dolorem quidem magnam quo ipsam placeat error illum consequatur. Praesentium, tenetur?
      Repellat reprehenderit tenetur quia eaque tempora consectetur recusandae. Et facilis aliquam perspiciatis a laboriosam nesciunt voluptatum illum accusamus architecto facere cumque commodi quae exercitationem laudantium, nam tempore, quasi id ipsum?
      Quae asperiores minima a distinctio ullam, quas dolorum possimus aliquam cum laborum cupiditate perferendis sint, doloremque corporis? Deleniti, nostrum deserunt, veritatis non earum expedita impedit enim repellendus repellat perspiciatis rerum!
      Excepturi odio, ratione impedit, repellendus tenetur, commodi minus animi tempora temporibus unde dignissimos! Deleniti voluptas doloribus corporis qui consectetur. Aliquid tempora ex et vitae sunt, quas tempore sed ullam vero!
      Reiciendis ducimus quidem modi deserunt cum reprehenderit, cumque qui asperiores maxime tenetur. Cupiditate fugiat, dolores dolore, facilis, earum quo repellat nisi vitae ipsam itaque hic ipsum! Quo labore vero explicabo?
      Aspernatur ullam minima tenetur illum ipsum quos hic a, ut modi accusantium inventore voluptatem iure vel cumque facere reiciendis ex. Sapiente quod ipsum sed eligendi alias fugiat! Eaque, aliquid molestias?
      Sapiente quos, dolorum reprehenderit distinctio dicta qui facere numquam quasi mollitia adipisci nam error optio aliquid. Cum tenetur asperiores quibusdam assumenda minima. Commodi nemo earum hic veniam quas, iure quibusdam.
      Maiores dolorum voluptatem laudantium minima saepe temporibus fuga laborum sequi aliquid rerum autem corporis vel ullam ut eum, repellendus commodi, similique dolores dignissimos reprehenderit pariatur eius! Ad blanditiis assumenda modi.
      Animi accusantium officiis dolor, odit adipisci consequuntur sequi fugiat mollitia optio iure explicabo eos accusamus possimus dolore impedit rem nihil et reprehenderit maiores a. Hic impedit doloribus possimus natus assumenda.
      Explicabo perferendis magni iusto possimus ducimus dolorum temporibus obcaecati nihil, placeat libero adipisci, laudantium quisquam minima accusantium accusamus officiis quibusdam voluptatum, nulla quos! Exercitationem nostrum doloribus aliquid tempore, expedita eaque!
      Blanditiis tempora ipsam, ipsum perspiciatis minus totam rem architecto iure vitae autem assumenda odit eos repudiandae eius veritatis iusto necessitatibus ipsa? Sit dolorum necessitatibus distinctio veniam ipsum ab, quidem cumque.
      Sit totam asperiores excepturi porro ex vero ipsa at, aliquam, incidunt non molestias? Maiores iusto eaque aspernatur possimus atque deserunt. Soluta facere aperiam omnis ratione consequuntur eligendi? Adipisci, voluptate suscipit.
      Dolor, nesciunt deleniti sed numquam quasi hic repudiandae cumque et corrupti fuga voluptate labore voluptates obcaecati, corporis excepturi, ut id consequuntur doloribus temporibus odit quaerat! Ipsum repellendus laborum impedit saepe.
      Laboriosam dolores velit aliquid provident blanditiis placeat quidem eaque nostrum, a voluptatibus architecto deleniti, vitae ipsum voluptate corporis. Unde ea velit quas voluptatum, officia molestias nesciunt provident vero cum quia.
      Deleniti sed voluptatibus perferendis aut sint, consectetur alias optio necessitatibus, facilis minus debitis impedit cum minima consequatur voluptatem soluta. Illum voluptas quod, provident ut optio numquam! Qui eligendi voluptates voluptatibus?
      Soluta ratione quaerat dolor maxime voluptatem dignissimos blanditiis, ad tenetur magnam facilis sed, ex quia laboriosam repellendus fugit? Nemo sequi assumenda saepe necessitatibus minus unde similique qui modi tempore dicta?
      Explicabo deserunt dolorem beatae, ratione minima magnam earum itaque fugiat ducimus mollitia vero! Sit amet, iste tenetur in alias doloribus voluptate cumque itaque incidunt assumenda velit dolore laudantium, dolorum nobis?
      Minima alias maiores eligendi dolore doloribus quo exercitationem nihil similique nisi! Corporis, a vel. Rerum eius, in sequi iste consectetur eligendi corrupti aliquid laudantium odio dignissimos unde exercitationem aspernatur cum.
      Features
    </div>
  );
}

export default Features